# tombi: format.rules.table-keys-order.disabled = true
[workspace]
name = "catter"
version = "0.0.1"
description = "A new tool to capture C++ compilation command"
authors = [
  "star9029 <hengxing9029@outlook.com>",
  "clice contributors <clice@clice.io>",
]
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
documentation = "https://clice.io"
repository = "https://github.com/clice-io/catter"
channels = ["conda-forge", "https://clice-io.github.io/conda-channel"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[dependencies]
pnpm = "*"

[target.win-64.dependencies]
vs2022_win-64 = "==19.44.35207"
vc14_runtime = "==14.44.35208"
ucrt = "==10.0.26100.0"

[target.linux-64.dependencies]
sysroot_linux-64 = "==2.17"
gcc = "==14.2.0"
gxx = "==14.2.0"

[target.osx-arm64.dependencies]
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
llvm-tools = "==20.1.8"
compiler-rt = "==20.1.8"
libcxx = "==20.1.8"

[target.unix.activation.env]
PATH = "$PIXI_PROJECT_ROOT/api/node_modules/.bin:$PATH"

[target.win-64.activation.env]
CATTER_DEFAULT_TOOLCHAIN = "msvc"
PATH = "%PIXI_PROJECT_ROOT%/api/node_modules/.bin;%PATH%"

[target.linux.activation.env]
CATTER_DEFAULT_TOOLCHAIN = "gcc"

[target.osx.activation.env]
CATTER_DEFAULT_TOOLCHAIN = "clang"

[feature.clang.dependencies]
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
llvm-tools = "==20.1.8"
compiler-rt = "==20.1.8"

[feature.dev.dependencies]
python = ">=3.14.2,<3.15"
nodejs = "==24.4.0"
lit = "*"
llvm-filecheck = ">=20.1.8,<22"

[feature.dev.pypi-dependencies]
pre-commit = "*"

[feature.dev.tasks]
format = "pre-commit run --all-files"
unit-test = "xmake test --verbose"
integration-test = "lit ./tests/integration -sav"
ut = [{ task = "unit-test"}]
it = [{ task = "integration-test"}]
test = [{ task = "ut"},{ task = "it"}]

[environments]
dev = ["dev"]
clang = ["dev", "clang"]

[tasks]
npm-install = { cmd = "pnpm install", inputs = [
  "pnpm-lock.yaml",
  "package.json"
] }
build = "xmake --verbose --diagnosis"

[tasks.cfg]
args = [
  {arg = "mode", choices = ["debug", "release"] },
  {arg = "toolchain", choices = ["msvc", "clang", "gcc", "default"], default = "default"},
]
cmd = """xmake config --clean --yes --test=y --mode={{ mode }} --toolchain=\
{% if toolchain == "default" %}$CATTER_DEFAULT_TOOLCHAIN{% else %}{{ toolchain }}{% endif %}"""

[tasks.ci-build]
args = [
  { "arg" = "mode", "choices" = ["debug", "release"] },
]
depends-on = [
  { task = "npm-install" },
  { task = "cfg", args = ["{{ mode }}"] },
  { task = "build" },
  { task = "test" }
]

[tasks.ci-check]
depends-on = [
  { task = "npm-install" },
  { task = "format" },
]

[tasks.build-js-lib]
cmd = "rm -rf ./api/output && run-p bundle-dts bundle-js"
cwd = "api"

[tasks.build-js-test]
cmd = "tsc --project tsconfig.test.json"
cwd = "api"
depends-on = "build-js-lib"
