target("ut-catter")
    set_kind("binary")
    add_rules("js-test")
    add_files("../../../api/src/*.ts", "../../../api/test/*.ts", "../../../api/test/res/**/*.txt")
    add_files("main.cc")
    add_files("tests/*.cc")
    add_packages("boost_ut")
    add_deps("catter-core", "libconfig", "librpc", "libutil")
    before_build(function (target)
        local data = path.absolute("api/output/test/")
        io.print("src/common/libconfig/include/libconfig/js-test.inc", "R\"(%s)\"", data)
    end)
