// Generated by scripts/js-gen/generate_llvm_option.mjs.

import { option_get_info, option_parse } from "catter-c";
import type { OptionInfo, OptionItem, OptionTable } from "catter-c";

export { ClangID } from "./clang.js";
export { ClangFlag } from "./clang.js";
export { ClangVisibility } from "./clang.js";
export { ClangDriverClass } from "./clang.js";
export { LldCoffID } from "./lld-coff.js";
export { LldCoffFlag } from "./lld-coff.js";
export { LldCoffVisibility } from "./lld-coff.js";
export { LldElfID } from "./lld-elf.js";
export { LldElfFlag } from "./lld-elf.js";
export { LldElfVisibility } from "./lld-elf.js";
export { LldMachOID } from "./lld-macho.js";
export { LldMachOFlag } from "./lld-macho.js";
export { LldMachOVisibility } from "./lld-macho.js";
export { LldMinGWID } from "./lld-mingw.js";
export { LldMinGWFlag } from "./lld-mingw.js";
export { LldMinGWVisibility } from "./lld-mingw.js";
export { LldWasmID } from "./lld-wasm.js";
export { LldWasmFlag } from "./lld-wasm.js";
export { LldWasmVisibility } from "./lld-wasm.js";
export { LlvmDlltoolID } from "./llvm-dlltool.js";
export { LlvmDlltoolFlag } from "./llvm-dlltool.js";
export { LlvmDlltoolVisibility } from "./llvm-dlltool.js";
export { LlvmLibID } from "./llvm-lib.js";
export { LlvmLibFlag } from "./llvm-lib.js";
export { LlvmLibVisibility } from "./llvm-lib.js";
export { NvccID } from "./nvcc.js";
export { NvccFlag } from "./nvcc.js";
export { NvccVisibility } from "./nvcc.js";

const RENDER_JOINED = 1 << 2;
const RENDER_SEPARATE = 1 << 3;
const OptionKindClass: {
  GroupClass: number;
  InputClass: number;
  UnknownClass: number;
  FlagClass: number;
  JoinedClass: number;
  ValuesClass: number;
  SeparateClass: number;
  RemainingArgsClass: number;
  RemainingArgsJoinedClass: number;
  CommaJoinedClass: number;
  MultiArgClass: number;
  JoinedOrSeparateClass: number;
  JoinedAndSeparateClass: number;
} = {
  GroupClass: 0,
  InputClass: 1,
  UnknownClass: 2,
  FlagClass: 3,
  JoinedClass: 4,
  ValuesClass: 5,
  SeparateClass: 6,
  RemainingArgsClass: 7,
  RemainingArgsJoinedClass: 8,
  CommaJoinedClass: 9,
  MultiArgClass: 10,
  JoinedOrSeparateClass: 11,
  JoinedAndSeparateClass: 12,
};

function cloneOptionItem(item: OptionItem): OptionItem {
  return {
    ...item,
    values: [...item.values],
  };
}

function joinedTokens(key: string, values: string[]): string[] {
  if (values.length === 0) {
    return [key];
  }
  return [key + values[0], ...values.slice(1)];
}

function renderTokens(info: OptionInfo, item: OptionItem): string[] {
  if (info.flags & RENDER_JOINED) {
    return joinedTokens(item.key, item.values);
  }
  if (info.flags & RENDER_SEPARATE) {
    return [item.key, ...item.values];
  }

  switch (info.kind) {
    case OptionKindClass.GroupClass:
    case OptionKindClass.InputClass:
    case OptionKindClass.UnknownClass:
      return [item.key];
    case OptionKindClass.FlagClass:
    case OptionKindClass.ValuesClass:
    case OptionKindClass.SeparateClass:
    case OptionKindClass.JoinedOrSeparateClass:
    case OptionKindClass.RemainingArgsClass:
    case OptionKindClass.MultiArgClass:
      return [item.key, ...item.values];
    case OptionKindClass.JoinedClass:
    case OptionKindClass.RemainingArgsJoinedClass:
      return joinedTokens(item.key, item.values);
    case OptionKindClass.CommaJoinedClass:
      return item.values.length === 0
        ? [item.key]
        : [item.key + item.values.join(",")];
    case OptionKindClass.JoinedAndSeparateClass:
      return joinedTokens(item.key, item.values);
    default:
      return [item.key, ...item.values];
  }
}

export function convertToUnalias(
  table: OptionTable,
  item: OptionItem,
): OptionItem {
  if (item.unalias === undefined) {
    return item;
  }

  const aliasInfo = option_get_info(table, item.id);
  const unaliasInfo = option_get_info(table, item.unalias);

  item.id = item.unalias;
  item.unalias = undefined;
  if (
    unaliasInfo.kind !== OptionKindClass.InputClass &&
    unaliasInfo.kind !== OptionKindClass.UnknownClass
  ) {
    item.key = unaliasInfo.prefixedKey;
  }
  item.values.push(...aliasInfo.aliasArgs);
  if (
    aliasInfo.kind === OptionKindClass.FlagClass &&
    aliasInfo.aliasArgs.length === 0 &&
    unaliasInfo.kind === OptionKindClass.JoinedClass
  ) {
    item.values.push("");
  }

  return item;
}

export function stringify(table: OptionTable, item: OptionItem): string {
  const renderItem =
    item.unalias === undefined
      ? item
      : convertToUnalias(table, cloneOptionItem(item));
  const info = option_get_info(table, renderItem.id);
  return renderTokens(info, renderItem).join(" ");
}

export function collect(
  table: OptionTable,
  args: string[],
): OptionItem[] | string {
  let res: OptionItem[] | string = [];
  option_parse(table, args, (parseRes) => {
    if (typeof parseRes === "string") {
      res = parseRes;
      return false;
    }
    (res as OptionItem[]).push(parseRes);
    return true;
  });
  return res;
}

export function replace(
  table: OptionTable,
  args: string[],
  cb: (
    parseRes: string | Readonly<OptionItem>,
  ) => OptionItem | boolean | undefined | string | string[],
): string {
  let nextToAdd = 0;
  let prevIndex = -1;
  let newPart = "";
  let finalArgs: string[] = [];
  const concatParts = (endIndex: number) => {
    finalArgs = finalArgs.concat([
      ...args.slice(nextToAdd, prevIndex),
      newPart,
    ]);
    nextToAdd = endIndex;
  };
  option_parse(table, args, (parseRes) => {
    if (prevIndex != -1) {
      concatParts(typeof parseRes === "string" ? args.length : parseRes.index);
      prevIndex = -1;
    }
    const cbRes = cb(parseRes);
    if (cbRes === undefined) {
      return true;
    }
    if (typeof cbRes === "boolean") {
      return cbRes;
    }

    if (typeof cbRes === "string") {
      newPart = cbRes;
    } else if (Array.isArray(cbRes)) {
      newPart = cbRes.join(" ");
    } else {
      newPart = stringify(table, cbRes);
    }

    if (typeof parseRes !== "string") {
      prevIndex = parseRes.index;
    }
    return true;
  });
  if (prevIndex != -1) {
    concatParts(args.length);
  }
  prevIndex = args.length;
  concatParts(-1);
  finalArgs.pop();
  return finalArgs.join(" ");
}
