// Generated by scripts/js-gen/generate_llvm_option.mjs.
// Source: /home/kacent/project/catter/.pixi/envs/dev/include/llvm-options-td/llvm-lib-Options.inc

export enum LlvmLibID {
  ID_INVALID = 0,
  ID_INPUT,
  ID_UNKNOWN,
  ID_deffile,
  ID_nativedeffile,
  ID_help,
  ID_ignore,
  ID_libpath,
  ID_lst,
  ID_llvmlibempty,
  ID_llvmlibindex_no,
  ID_llvmlibindex,
  ID_llvmlibthin,
  ID_ltcg,
  ID_machine,
  ID_nodefaultlib,
  ID_nodefaultlib_all,
  ID_nologo,
  ID_out,
  ID_subsystem,
  ID_verbose,
  ID_WX_no,
  ID_WX,
  ID_help_q,
}

export enum LlvmLibFlag {
  None = 0,
}

export enum LlvmLibVisibility {
  None = 0,
  DefaultVis = 1,
}
