import * as io from "catter/io";
io.println("\n----Running I/O tests...----");
io.print("Hello, World!");
io.println("This is a new line.");
io.coloredPrint("This is red text.", "red");
io.coloredPrintln("This is green text with a newline.", "green");
io.coloredPrint("This is yellow text.", "yellow");
io.coloredPrintln("This is blue text with a newline.", "blue");
io.coloredPrint("This is blue text.", "blue");
io.coloredPrintln("This is yellow text with a newline.", "yellow");
io.println("----I/O tests completed.----\n");
