import { coloredPrint, coloredPrintln, print, println } from "catter/io";
println("\n----Running I/O tests...----");
print("Hello, World!");
println("This is a new line.");
coloredPrint("This is red text.", "red");
coloredPrintln("This is green text with a newline.", "green");
coloredPrint("This is yellow text.", "yellow");
coloredPrintln("This is blue text with a newline.", "blue");
coloredPrint("This is blue text.", "blue");
coloredPrintln("This is yellow text with a newline.", "yellow");
println("----I/O tests completed.----\n");
